[2023-04-16T15:30:09.580+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preparo_receita_almoco.verificar_tempo_preparo manual__2023-04-16T15:30:06.973776+00:00 [queued]>
[2023-04-16T15:30:09.588+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preparo_receita_almoco.verificar_tempo_preparo manual__2023-04-16T15:30:06.973776+00:00 [queued]>
[2023-04-16T15:30:09.589+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-16T15:30:09.589+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-16T15:30:09.590+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-16T15:30:09.600+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): verificar_tempo_preparo> on 2023-04-16 15:30:06.973776+00:00
[2023-04-16T15:30:09.608+0000] {standard_task_runner.py:55} INFO - Started process 126 to run task
[2023-04-16T15:30:09.613+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'preparo_receita_almoco', 'verificar_tempo_preparo', 'manual__2023-04-16T15:30:06.973776+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/preparo_receita_almoco_dag.py', '--cfg-path', '/tmp/tmprctbfrjr']
[2023-04-16T15:30:09.614+0000] {standard_task_runner.py:83} INFO - Job 208: Subtask verificar_tempo_preparo
[2023-04-16T15:30:09.699+0000] {task_command.py:388} INFO - Running <TaskInstance: preparo_receita_almoco.verificar_tempo_preparo manual__2023-04-16T15:30:06.973776+00:00 [running]> on host 74f80fb1551d
[2023-04-16T15:30:09.770+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=preparo_receita_almoco
AIRFLOW_CTX_TASK_ID=verificar_tempo_preparo
AIRFLOW_CTX_EXECUTION_DATE=2023-04-16T15:30:06.973776+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-16T15:30:06.973776+00:00
[2023-04-16T15:30:09.779+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/preparo_receita_almoco_dag.py", line 41, in verificar_tempo_preparo
    raise ValueError('Não há tempo suficiente para preparar a receita.')
ValueError: Não há tempo suficiente para preparar a receita.
[2023-04-16T15:30:09.789+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=preparo_receita_almoco, task_id=verificar_tempo_preparo, execution_date=20230416T153006, start_date=20230416T153009, end_date=20230416T153009
[2023-04-16T15:30:09.799+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 208 for task verificar_tempo_preparo (Não há tempo suficiente para preparar a receita.; 126)
[2023-04-16T15:30:09.825+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-16T15:30:09.845+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
