[2023-04-16T15:07:29.312+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preparo_receita_almoco.verificar_tempo_preparo manual__2023-04-16T15:07:26.142933+00:00 [queued]>
[2023-04-16T15:07:29.330+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preparo_receita_almoco.verificar_tempo_preparo manual__2023-04-16T15:07:26.142933+00:00 [queued]>
[2023-04-16T15:07:29.332+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-16T15:07:29.333+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-16T15:07:29.335+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-16T15:07:29.409+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): verificar_tempo_preparo> on 2023-04-16 15:07:26.142933+00:00
[2023-04-16T15:07:29.425+0000] {standard_task_runner.py:55} INFO - Started process 66 to run task
[2023-04-16T15:07:29.430+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'preparo_receita_almoco', 'verificar_tempo_preparo', 'manual__2023-04-16T15:07:26.142933+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/preparo_receita_almoco_dag.py', '--cfg-path', '/tmp/tmp4taz_k42']
[2023-04-16T15:07:29.432+0000] {standard_task_runner.py:83} INFO - Job 179: Subtask verificar_tempo_preparo
[2023-04-16T15:07:29.564+0000] {task_command.py:388} INFO - Running <TaskInstance: preparo_receita_almoco.verificar_tempo_preparo manual__2023-04-16T15:07:26.142933+00:00 [running]> on host 74f80fb1551d
[2023-04-16T15:07:29.675+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=preparo_receita_almoco
AIRFLOW_CTX_TASK_ID=verificar_tempo_preparo
AIRFLOW_CTX_EXECUTION_DATE=2023-04-16T15:07:26.142933+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-16T15:07:26.142933+00:00
[2023-04-16T15:07:29.692+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/preparo_receita_almoco_dag.py", line 35, in verificar_tempo_preparo
    raise ValueError('Não há tempo suficiente para preparar a receita.')
ValueError: Não há tempo suficiente para preparar a receita.
[2023-04-16T15:07:29.718+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=preparo_receita_almoco, task_id=verificar_tempo_preparo, execution_date=20230416T150726, start_date=20230416T150729, end_date=20230416T150729
[2023-04-16T15:07:29.743+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 179 for task verificar_tempo_preparo (Não há tempo suficiente para preparar a receita.; 66)
[2023-04-16T15:07:29.788+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-16T15:07:29.819+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
