[2023-04-15T10:49:38.052+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_executa_sql.criar_tabela_db scheduled__2023-04-15T09:30:00+00:00 [queued]>
[2023-04-15T10:49:38.133+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_executa_sql.criar_tabela_db scheduled__2023-04-15T09:30:00+00:00 [queued]>
[2023-04-15T10:49:38.141+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-15T10:49:38.147+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-15T10:49:38.149+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-15T10:49:38.247+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): criar_tabela_db> on 2023-04-15 09:30:00+00:00
[2023-04-15T10:49:38.282+0000] {standard_task_runner.py:55} INFO - Started process 718 to run task
[2023-04-15T10:49:38.300+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_executa_sql', 'criar_tabela_db', 'scheduled__2023-04-15T09:30:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/dag_executa_sql.py', '--cfg-path', '/tmp/tmphsn8kcmi']
[2023-04-15T10:49:38.303+0000] {standard_task_runner.py:83} INFO - Job 107: Subtask criar_tabela_db
[2023-04-15T10:49:38.534+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_executa_sql.criar_tabela_db scheduled__2023-04-15T09:30:00+00:00 [running]> on host 229ecb906897
[2023-04-15T10:49:38.615+0000] {abstractoperator.py:615} ERROR - Exception rendering Jinja template for task 'criar_tabela_db', field 'sql'. Template: 'criar_tabela_db.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-15T10:49:38.622+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2023-04-15T10:49:38.652+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=dag_executa_sql, task_id=criar_tabela_db, execution_date=20230415T093000, start_date=20230415T104938, end_date=20230415T104938
[2023-04-15T10:49:38.680+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 107 for task criar_tabela_db (criar_tabela_db.sql; 718)
[2023-04-15T10:49:38.730+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-15T10:49:38.820+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
