[2023-04-16T15:47:57.937+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preparo_receita_almoco.formatar_receita manual__2023-04-16T15:47:55.805410+00:00 [queued]>
[2023-04-16T15:47:57.952+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preparo_receita_almoco.formatar_receita manual__2023-04-16T15:47:55.805410+00:00 [queued]>
[2023-04-16T15:47:57.959+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-16T15:47:57.961+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-16T15:47:57.961+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-16T15:47:58.008+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): formatar_receita> on 2023-04-16 15:47:55.805410+00:00
[2023-04-16T15:47:58.018+0000] {standard_task_runner.py:55} INFO - Started process 65 to run task
[2023-04-16T15:47:58.027+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'preparo_receita_almoco', 'formatar_receita', 'manual__2023-04-16T15:47:55.805410+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/preparo_receita_almoco_dag.py', '--cfg-path', '/tmp/tmp8d_3srnr']
[2023-04-16T15:47:58.029+0000] {standard_task_runner.py:83} INFO - Job 226: Subtask formatar_receita
[2023-04-16T15:47:58.162+0000] {task_command.py:388} INFO - Running <TaskInstance: preparo_receita_almoco.formatar_receita manual__2023-04-16T15:47:55.805410+00:00 [running]> on host 74f80fb1551d
[2023-04-16T15:47:58.291+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=preparo_receita_almoco
AIRFLOW_CTX_TASK_ID=formatar_receita
AIRFLOW_CTX_EXECUTION_DATE=2023-04-16T15:47:55.805410+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-16T15:47:55.805410+00:00
[2023-04-16T15:47:58.297+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/preparo_receita_almoco_dag.py", line 53, in formatar_receita
    raise ValueError('Informações insuficientes na receita de almoço.')
ValueError: Informações insuficientes na receita de almoço.
[2023-04-16T15:47:58.310+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=preparo_receita_almoco, task_id=formatar_receita, execution_date=20230416T154755, start_date=20230416T154757, end_date=20230416T154758
[2023-04-16T15:47:58.336+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 226 for task formatar_receita (Informações insuficientes na receita de almoço.; 65)
[2023-04-16T15:47:58.399+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-16T15:47:58.432+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
